spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcls
    username: abarrasa
    password: hiberus1000
    driverClassName: oracle.jdbc.driver.OracleDriver
jpa:
  show-sql: true
  open-in-view: false
  hibernate:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.Oracle10gDialect
